version: "3.8"

services:

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  rag_agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: rag_agent
    command: uvicorn agent_servers.rag_server:app --host 0.0.0.0 --port 9001 --reload
    ports:
      - "9001:9001"
    env_file:
      - .env
    volumes:
    - ./agent_servers:/app/agent_servers
    - ./backend:/app/backend